services:
  latios:
    user: root
    container_name: latios
    image: ghcr.io/timundcokg/latios:latest
    depends_on:
      - latios-db
    environment:
      DB_HOST: latios-db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: latios
      DB_PORT: 5432
      CF_API_TOKEN: test_string
      LATIOS_AUTH_COOKIE: test_cookie_value
      LATIOS_AUTH_TOKEN: test_token_value
      DOMAIN: timsalokat.local
      FALLBACK_USER: testuser
      FALLBACK_PASSWORD: testpass
      ENVIRONMENT: dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - latios-network

  latios-db:
    container_name: latios-db
    image: postgres:16
    environment:
      POSTGRES_DB: latios
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    # Remove persistent volume for dev
    # volumes:
    #   - /opt/latios/data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - latios-network

networks:
  latios-network:
    name: latios-network
    driver: bridge
